### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'int' 

### ISSUE THREAD

**Issue by salhasalman** [hayj/DeepStyle#2]
@hayj 
 from keras.layers.embeddings import Embedding
emb = Embedding(config["wordVectorsPattern"], config["embeddingsDimension"], verbose=True, logger=logger)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-76-ef068d430d9a> in <module>()
----> 1 emb = Embedding(config["wordVectorsPattern"], config["embeddingsDimension"], verbose=True, logger=logger)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/embeddings.py in __init__(self, input_dim, output_dim, embeddings_initializer, embeddings_regularizer, activity_regularizer, embeddings_constraint, mask_zero, input_length, **kwargs)
    104       else:
    105         kwargs['input_shape'] = (None,)
--> 106     if input_dim <= 0 or output_dim <= 0:
    107       raise ValueError('Both `input_dim` and `output_dim` should be positive, '
    108                        'found input_dim {} and output_dim {}'.format(

TypeError: '<=' not supported between instances of 'str' and 'int'

How to solve this issue.

**Comment by hayj** [comment]
What do you want to do exactly?
You tried the sna-train notebook?
For the DBert-ft model it's [this notebook](https://github.com/hayj/DeepStyle/blob/master/experiments/notebooks/dbert-ft-train.ipynb).

**Comment by salhasalman** [comment]
@hayj 
yeah i am training the sna-train notebook.then it showed this error.though i tried to convert str to int ,it didnt work.Since im stucked here.couldnt proceed.Can you help me to solve this issue?

**Comment by hayj** [comment]
Your `config["embeddingsDimension"]` is a str?

**Comment by salhasalman** [comment]
@hayj 
config = \
{
    "patience": 3 if TEST else 20, # <IMPORTANT>
    # 3gramsFiltered, 2gramsFiltered, 1gramsFiltered, textSentences # <IMPORTANT>
    # filtered_sentences, sentences
    "dataCol": "filtered_sentences", # <IMPORTANT>
    "wordVectorsPattern": "test" if TEST else "glove-840B", # <IMPORTANT>
    "embeddingsDimension": 100 if TEST else 300,
    "minVocDF": 2, # 10 if isNotebook else 2,
    "minVocLF": 2,
    "minTokensLength": 3,
    "docLength": 1200, # The size of documents representation (median * 3 = 600)
    "isTrainableEmbeddings": False,
    "doMultiGPU": False, # not isNotebook
    "batchSize": 32 if TEST else 128, # 128, 256 # <IMPORTANT>
    "epochs": 10 if TEST else 1000,
    "maxQueueSize": 10 if TEST else 10,
    "saveFinalModel": False,
    "doNotif": True, # not isNotebook,
    "attention": False, # <IMPORTANT>
    "bidirectional": False, # <IMPORTANT>
    "isCuDNN": True, # <IMPORTANT>
    "saveMetrics":
    {
        "val_loss": "min",
        "val_acc": "max",
        "val_top_k_categorical_accuracy": "max",
    },
    "metrics": ['accuracy', 'top_k_categorical_accuracy'], # ['sparse_categorical_accuracy', 'sparse_top_k_categorical_accuracy'], ['accuracy', 'top_k_categorical_accuracy']
    "loss": 'categorical_crossentropy', # sparse_categorical_crossentropy, categorical_crossentropy
    "trainStepDivider": 80 if TEST else 0, # 5 à la base......
    "infiniteBatcherShuffle": 0 if TEST else 0,
    
    "inputEncoding": "embedding", # index, embedding
    "labelEncoding": 'onehot', # onehot, index
    
    "denseUnits": [500, 100], # [100], [500, 100]
    "rnnUnits": 500,
    
    "persist": [False, False] if TEST else [False, False],
}
if config["isCuDNN"]:
    del config["isCuDNN"]

No I think config["wordVectorsPattern"] is a string

**Comment by hayj** [comment]
Sorry but this notebook is not maintained, you need to adapt it step by step according to your Keras version, etc (that said, you can get inspiration from it).

**Comment by salhasalman** [comment]
oh i see..okay
